app/models.py
from datetime import datetime
from app.extentions import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app.extentions import login

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(19), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class WebApps(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    description = db.Column(db.String())
    url = db.Column(db.String())
    img_url = db.Column(db.String())

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/forms.py
from wtforms import StringField, BooleanField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo
from flask_wtf import FlaskForm


class User_Add(FlaskForm):
    username = StringField('Логин', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired(), EqualTo('password_confirm')])
    password_confirm = PasswordField('Пароль Повторно', validators=[DataRequired()])
    submit = SubmitField("Создать")
    
class User_log(FlaskForm):
    username = StringField('Логин')
    password = PasswordField('Пароль')
    remember_me = BooleanField("Запомнить", default = False)
    submit = SubmitField("войти")


class WebApps_add(FlaskForm):
    title = StringField('Название', validators=[DataRequired()])
    description = StringField('Описание', validators=[DataRequired()])
    url = StringField('Ссылка на сервис', validators=[DataRequired()])
    img_url = StringField('Ссылка на картинку', validators=[DataRequired()])
    submit = SubmitField("Добавить")

app/__init__.py
from flask import Flask, render_template
import configparser
from .routes.index import index_bp
import os
from .extentions import db, migrate, login

config = configparser.RawConfigParser()   
config.read("./config.conf")



app = Flask(__name__, static_folder='static/')
app.config['SECRET_KEY'] = "3aecf0fa3c22de921cba843775b268f2ca846a94"
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = f'postgresql://{config.get("postgres", "user")}:{config.get("postgres", "password")}@{config.get("postgres", "url")}:{config.get("postgres", "port")}/{config.get("postgres", "db")}' 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)
migrate.init_app(app, db)
login.init_app(app)

app.register_blueprint(index_bp)

app/routes/index.py
from app.models import User, WebApps
from app.extentions import db
from flask import flash, render_template, Blueprint, redirect, url_for, request
from flask_wtf import FlaskForm
from flask_login import current_user, login_user, logout_user, login_required
from app.forms import User_Add, User_log, WebApps_add
from sqlalchemy import func

index_bp = Blueprint("index", __name__, url_prefix="/")

@index_bp.before_request
def before_request():
    db.create_all()
    if current_user.is_anonymous and \
    str(request.endpoint) == "index.setup" and \
    len(User.query.all()) != 0:
        return redirect(url_for("index.log"))

@index_bp.route("/")
@index_bp.route("/index", methods=['GET','POST'])
def main():
    
    if len(User.query.all()) == 0:
        return redirect(url_for("index.setup"))
    else:
        services = WebApps.query.all()
        if request.method == "POST":
            name = str(request.form.get("search"))
            print(name)
            services = WebApps.query.filter(WebApps.title.ilike(f'%{name}%')).all()
            
        return render_template("index.html", services=services, user=current_user)

@index_bp.route("/app/add", methods=['GET','POST'])
@login_required
def app_add():
    form = WebApps_add()
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        img_url = form.img_url.data
        url = form.url.data
        
        obj = WebApps(title=title,description=description,url=url,img_url=img_url)
        db.session.add(obj)
        db.session.commit()
        return redirect(url_for("index.main"))
    return render_template("app_add.html", form=form, user=current_user)

@index_bp.route("/app/del/<int:app>", methods=['GET','POST'])
@login_required
def app_del(app):
    obj = WebApps.query.get(app)
    db.session.delete(obj)
    db.session.commit()
    return redirect(url_for("index.main"))










@index_bp.route("/setup", methods=['GET','POST'])
def setup():
    form = User_Add()
    if form.validate_on_submit():
        user = form.username.data
        password = form.password.data
        obj = User(username=str(user))
        obj.set_password(str(password))
        db.session.add(obj)
        db.session.commit()
        return redirect(url_for("index.main"))
    return render_template("setup.html", form=form, user=current_user)

@index_bp.route("/app/settings/reset", methods=['GET','POST'])
def reset_all():
    database = WebApps.query.all()
    for obj in database:
        db.session.delete(obj)
    
    database = User.query.all()
    for obj in database:
        db.session.delete(obj)
    
    db.session.commit()
    return redirect(url_for("index.main"))

    
    
    
    
    
    
    
    
    
    
@index_bp.route("/auth/log", methods=['GET','POST'])
def log():
    if current_user.is_anonymous:
        form = User_log()
        if form.validate_on_submit():
            user = form.username.data
            password = form.password.data
            remember = form.remember_me.data
            obj = User.query.filter_by(username=user).first()
            if obj != None and obj.check_password(password) is True:
                print('login good')
                login_user(obj, remember)
                return redirect(url_for("index.main"))
            else:
                print('login error')
                flash("bad data")
            
        return render_template("log.html", form=form, user=current_user)
    else:
        return redirect(url_for("index.main"))
    
@index_bp.route("/auth/out", methods=['GET','POST'])
@login_required
def out():
    logout_user()
    return redirect(url_for('index.main'))
        

app/templates/app_add.html
{% extends 'base.html' %}

{% block head%}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/login.css') }}">
{% endblock %}


{% block content %}



<div class="login">
    <h2 class="active"> Добавить </h2>
  
    <h2 class="nonactive">Сервис</h2>
    <form action="" method="POST">
        {{ form.csrf_token }}
        <br>
        {{ form.title.label }} {{ form.title(size=20,autocomplete="off") }}
        <br>
        {{ form.description.label }} {{ form.description(size=20,autocomplete="off") }}
        <br>
        {{ form.url.label }} {{ form.url(size=20,autocomplete="off") }}
        <br>
        {{ form.img_url.label }} {{ form.img_url(size=20,autocomplete="off") }}
        <br>
        {{ form.submit }}
    </form>
  
  </div>


        

{% endblock %}
    

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block head %}

    {% endblock %}
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/navbar.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/content.css') }}">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <title>{{ title }}</title>
</head>
<body>
    <nav>
        <div class="menu-icon">
           <span class="fas fa-bars"></span>
        </div>
        <div class="logo">
           [ Сервисы ]
        </div>
        <div class="nav-items">
           <li><a href="{{url_for('index.main')}}">Главная</a></li>
           {%if user.is_anonymous %}
           <li><a href="{{url_for('index.log')}}">Вход</a></li>
           {% else %}
           <li><a href="{{url_for('index.app_add')}}">Добавить</a></li>
           <li><a href="{{url_for('index.out')}}">Выйти</a></li>
           {% endif %}

        </div>
        <div class="search-icon">
           <span class="fas fa-search"></span>
        </div>
        <div class="cancel-icon">
           <span class="fas fa-times"></span>
        </div>
        <form method="POST" action="/index">
           <input name="search" type="search" class="search-data" placeholder="Поиск" required>
           <button type="submit" class="fas fa-search"></button>
        </form>
     </nav>
     <div class="content">
        {% block content %}

        {% endblock %}
     </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block head%}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block content %}

<div class="grid">
    {%for app in services%}
    <div class="grid__item">
        <div class="card"><img class="card__img" src="{{app.img_url}}">
            <div class="card__content">
                <h1 class="card__header">{{app.title}}</h1>
                <p class="card__text">{{app.description}}</p>
                <a href="{{app.url}}"><button class="card__btn">Перейти</button></a>
                {%if user.is_authenticated %}
                <br>
                <a href="/app/del/{{app.id}}"><button class="card__btn">Удалить</button></a>
                {%endif%}
            </div>
        </div>
    </div>
    {%endfor%}
</div>


{% endblock %}

app/templates/log.html
{% extends 'base.html' %}

{% block head%}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/login.css') }}">
{% endblock %}


{% block content %}



<div class="login">
    <h2 class="active"> sign in </h2>
  
    <h2 class="nonactive"> sign up </h2>
    <form action="" method="POST">
        {{ form.csrf_token }}
        {{ form.username.label }}
        <br>
        {{ form.username(size=20) }}
        <br>
        {{ form.password.label }}
        <br>
        {{ form.password(size=20, type="password") }}
        <br>
        {{ form.remember_me.label }}
        {{ form.remember_me}}
        <br>
        {{ form.submit()}}
    </form>
  
  </div>


        

{% endblock %}

app/templates/setup.html
{% extends 'base.html' %}




{% block content %}

{%if user.is_authenticated %}
<a href="/app/settings/reset"><button>RESET ALL</button></a>
{%else%}
<form method="POST" action="">
    {{ form.csrf_token }}
    {{ form.username.label }} {{ form.username(size=20) }}
    {{ form.password.label }} {{ form.password(size=20) }}
    {{ form.password_confirm.label }} {{ form.password_confirm(size=20) }}
    {{ form.submit.label }} {{ form.submit(size=20) }}
</form>
{%endif%}

{% endblock %}